# Standard library
import asyncio
import json
import traceback
from typing import List

# Third-party
from fastapi import APIRouter, Depends, HTTPException, status
from fastapi.responses import StreamingResponse
from fastapi.security import HTTPAuthorizationCredentials, HTTPBearer
from sqlalchemy.orm import Session

# Local
from app.database import get_db
from app.models.conversations import Conversation
from app.models.message import Message
from app.models.user import User
from app.schemas.chat import ConversationResponse, ConversationWithMessages, MessageCreate, MessageResponse
from app.services.assistant_service import AssistantService
from app.utils.security import verify_token

router = APIRouter(prefix="/chat", tags=["Chat"])
security = HTTPBearer()


def get_current_user(
    credentials: HTTPAuthorizationCredentials = Depends(security),
    db: Session = Depends(get_db)
) -> User:
    """Get current authenticated user"""
    token = credentials.credentials
    email = verify_token(token)

    if not email:
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Invalid or expired token"
        )

    user = db.query(User).filter(User.email == email).first()
    if not user:
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="User not found"
        )

    return user


@router.post("/stream")
async def stream_chat_message(
    message: MessageCreate,
    conversation_id: int = None,
    user: User = Depends(get_current_user),
    db: Session = Depends(get_db)
):
    """
    Send a message and get streaming AI response using LangGraph.

    This endpoint uses astream_events to get token-level streaming from the
    LangGraph chatbot node, while the summarizer runs in parallel for title generation.

    If conversation_id is provided, adds to existing conversation.
    Otherwise, creates a new conversation.
    """
    # Initialize assistant service (uses LangGraph)
    assistant = AssistantService(db, user)

    # Get or create conversation
    if conversation_id:
        conversation = db.query(Conversation).filter(
            Conversation.id == conversation_id,
            Conversation.user_id == user.id
        ).first()

        if not conversation:
            raise HTTPException(
                status_code=status.HTTP_404_NOT_FOUND,
                detail="Conversation not found"
            )
    else:
        # Create new conversation
        conversation = Conversation(
            user_id=user.id,
            instructions=[]
        )
        db.add(conversation)
        db.commit()
        db.refresh(conversation)

    # Save user message
    user_message = Message(
        conversation_id=conversation.id,
        role="user",
        content=message.content
    )
    db.add(user_message)
    db.commit()
    db.refresh(user_message)

    # Track if this is a new conversation (title will come from LangGraph summarizer)
    is_new_conversation = not conversation_id and conversation.title == "New Chat"

    # Create async generator for SSE format
    async def event_generator():
        nonlocal conversation
        full_response = ""
        new_title = None

        # Send conversation metadata first
        metadata = {
            "type": "metadata",
            "conversation_id": conversation.id,
            "user_message_id": user_message.id,
            "instructions": conversation.instructions,
            "conversation_title": conversation.title
        }
        yield f"data: {json.dumps(metadata)}\n\n"

        # Stream chat response via LangGraph (astream_events)
        # The graph runs summarizer and chatbot in parallel:
        # - Summarizer generates title (for new conversations)
        # - Chatbot streams response tokens
        try:
            async for event in assistant.stream_chat(message.content, conversation):
                if event["type"] == "chunk":
                    # Stream response tokens to client
                    full_response += event["text"]
                    chunk_data = {"type": "chunk", "text": event["text"]}
                    yield f"data: {json.dumps(chunk_data)}\n\n"
                    await asyncio.sleep(0)

                elif event["type"] == "title":
                    # Title generated by summarizer node (runs in parallel)
                    new_title = event["title"]
                    if is_new_conversation and new_title and new_title != "New Chat":
                        # Update conversation title in DB
                        conversation.title = new_title
                        db.commit()
                        db.refresh(conversation)
                        # Send title update event to client
                        title_data = {"type": "title", "conversation_title": new_title}
                        yield f"data: {json.dumps(title_data)}\n\n"

                elif event["type"] == "error":
                    error_data = {"type": "error", "message": event["message"]}
                    yield f"data: {json.dumps(error_data)}\n\n"
                    return

                elif event["type"] == "complete":
                    full_response = event.get("full_response", full_response)
                    # Check if title came from complete event (fallback)
                    if not new_title and event.get("conversation_title"):
                        new_title = event["conversation_title"]
                        if is_new_conversation and new_title and new_title != "New Chat":
                            conversation.title = new_title
                            db.commit()
                            db.refresh(conversation)

        except Exception as e:
            traceback.print_exc()
            error_data = {"type": "error", "message": str(e)}
            yield f"data: {json.dumps(error_data)}\n\n"
            return

        # Save assistant response to database
        assistant_message = Message(
            conversation_id=conversation.id,
            role="assistant",
            content=full_response
        )
        db.add(assistant_message)
        db.commit()
        db.refresh(assistant_message)

        # Send completion event with final title
        completion_data = {
            "type": "complete",
            "assistant_message_id": assistant_message.id,
            "conversation_id": conversation.id,
            "conversation_title": conversation.title
        }
        yield f"data: {json.dumps(completion_data)}\n\n"

    return StreamingResponse(
        event_generator(),
        media_type="text/event-stream",
        headers={
            "Cache-Control": "no-cache",
            "Connection": "keep-alive",
            "X-Accel-Buffering": "no",
        }
    )


@router.get("/conversations", response_model=List[ConversationResponse])
def get_conversations(
    user: User = Depends(get_current_user),
    db: Session = Depends(get_db)
):
    """
    Get all conversations for current user.
    Ordered by most recent first.
    """
    conversations = db.query(Conversation).filter(
        Conversation.user_id == user.id
    ).order_by(Conversation.updated_at.desc()).all()

    return conversations


@router.get("/conversations/{conversation_id}", response_model=ConversationWithMessages)
def get_conversation(
    conversation_id: int,
    user: User = Depends(get_current_user),
    db: Session = Depends(get_db)
):
    """
    Get specific conversation with all messages.
    """
    conversation = db.query(Conversation).filter(
        Conversation.id == conversation_id,
        Conversation.user_id == user.id
    ).first()

    if not conversation:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Conversation not found"
        )

    return conversation


@router.delete("/conversations/{conversation_id}")
def delete_conversation(
    conversation_id: int,
    user: User = Depends(get_current_user),
    db: Session = Depends(get_db)
):
    """
    Delete a conversation and all its messages.
    """
    conversation = db.query(Conversation).filter(
        Conversation.id == conversation_id,
        Conversation.user_id == user.id
    ).first()

    if not conversation:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Conversation not found"
        )

    db.delete(conversation)
    db.commit()

    return {"message": "Conversation deleted successfully"}
